name: Run Benchmarks
on:
  pull_request:
    branches:
      - master

jobs:
  Benchmarking:
    container:
      image: vowpalwabbit/ubuntu1604-build:latest
    runs-on: ubuntu-latest
    steps:
      - name: Activate python36
        shell: bash
        run: sudo conda init bash ; conda activate test-python36
      - run: python --version
      - uses: actions/checkout@v1
        with:
          # ref: master // master doesn't have benchmark scripts this right now, check diff between two branch runs
          submodules: true
      - name: Install google benchmarks
        shell: bash
        run: ./.scripts/linux/install-benchmark.sh # repo dir
      - name: Build master
        shell: bash
        run: ./.scripts/linux/build-with-benchmarks.sh
      - name: Benchmark master
        shell: bash
        run: ./.scripts/linux/run-benchmarks.sh master-benchmarks.json # repo dir
      - run: ls
      - run: rm -rf benchmark build
      - name: Upload master benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: master-benchmarks
          path: master-benchmarks.json
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Download master benchmark results
        uses: actions/download-artifact@v2
        with:
          name: master-benchmarks
      - name: Install google benchmarks
        shell: bash
        run: ./.scripts/linux/install-benchmark.sh
      - name: Build branch
        shell: bash
        run: ./.scripts/linux/build-with-benchmarks.sh
      - name: Benchmark branch
        shell: bash
        run: ./.scripts/linux/run-benchmarks.sh branch-benchmarks.json
      - name: Install benchmark compare requirements
        shell: bash
        run: pip install -r benchmark/tools/requirements.txt
      - name: Compare benchmarks
        shell: bash
        run: ./.scripts/linux/compare-benchmarks.sh master-benchmarks.json branch-benchmarks.json
      - run: ls
